### ISSUE TITLE
iron-router-i18n is not working with iron-router-active

### ISSUE THREAD

**Issue by dohomi** [yoolab/iron-router-i18n#27]
Hi,
iron router breaks functionality with iron-router-active. I tried several ways with including iron-router-i18n before iron-router-active, but without success. The link is here reported as well, but I guess that package can't change anything about this issue: https://github.com/zimme/meteor-iron-router-active/issues/13

I tried to update iron-router-active with a weak dependency on iron-router-i18n without success.

**Comment by martinopic** [comment]
The module was not working with Iron Router i18N because it was using the Router created by Iron Router instead of the Router created by Iron Router i18n. It's a common problem, more on this on #32 .

Now it works but as i18n routes have a different name (usually based on path) from the default route sometime the behaviour is not the expected one (e.g. in the example page two route is called "two" for en route and "es.dos" for es route, regex "two" will just match the first one). I think this is the same problem raised by #33

**Comment by martinopic** [comment]
It must be noted that in order to work with iron-router-active iron-router-i18n must added/loaded BEFORE iron-router-active.

**Comment by martinopic** [comment]
After 51ce8d097236e393177a353b5087417eeff132c9 (see #32 ) there is not need to add/load iron-router-i18n before iron-router-active.
