### ISSUE TITLE
Browser's back button does not work.

### ISSUE THREAD

**Issue by y-ich** [yoolab/iron-router-i18n#43]

**Comment by catsoft** [comment]
+1. If there is a query after path like ?someField=something back button works..

**Comment by martinopic** [comment]
Not sure exactly what are you are referring to but while investigating the issue I've found one problem in default ```missingLangCodeAction``` (the action that is executed when is missing a language code from the url) which could cause this issue in some specific cases. Also the two sample application prevented the back button to work but just when clicking on the "Home" link but just because they weren't using the ```pathFor``` helper for home url.

In general it seems that whenever there is a redirect (```Router.go```) the back button is not working but this seems to be an Iron Router behaviour, not an Iron Router i18n behaviour. Are the cases you are reporting having to do with redirects (```Router.go``` / ```missingLangCodeAction``` cases)?

Please test it the patch I've done on master works for your cases, if not I'll need more details to address the issue because as far as I can see the back button is now correctly working (see sample apps in "examples" folder).

**Comment by y-ich** [comment]
I made reproduction code.
https://github.com/y-ich/ir-i18n-reproduction
If no Iron Router i18n, back button works.
Event the latest iron-router i18n did not resolve this issue.

**Comment by martinopic** [comment]
Hi @y-ich, that's exactly what I tried to explain above: whenever you hit a url with no language code (e.g. ```/sub```) default ```missingCodeLang``` will redirect (```Router.go```) to the corresponding route with language code (in your case ```/en/sub```) and Iron Router (not Iron Router i18n) stops back button function whenever you have a redirect.

The solution is as simple as using ```pathFor``` instead of hardcoded urls (which is a good idea in any case), in your case would be using ```{{ pathFor 'sub'}}```, I tested it with your simple app and back button correctly works with 0.5.3 in this case ;-)

**Comment by y-ich** [comment]
Now I understood.
Thank you!

**Comment by martinopic** [comment]
As a second thought I realized that even if I strongly suggest to use ```pathFor``` / ```urlFor``` helpers it would be still a desirable feature not to block the browser navigation history on a missing lang code -> lang code route redirection so I added this. Thanks @y-ich (now you sample app works even without using ```pathFor``` even if its use is still recommended)  :-)
