### ISSUE TITLE
ReferenceError: I18NConf is not defined

### ISSUE THREAD

**Issue by paulo2nd** [yoolab/iron-router-i18n#62]
I've added iron-router-i18n in my project, but after trying to use the I18NConf.configure I got the error: ReferenceError: I18NConf is not defined. (Trying to use it in my router.js).

**Comment by paulo2nd** [comment]
had to add martino:i18n-conf manually.

**Comment by martinopic** [comment]
Which version are you using? There is a (non weak) dependency since version 1.0.0 so martino:i18n-conf should be loaded automatically.

**Comment by paulo2nd** [comment]
Meteor 1.1.0.2, martino:iron-router-i18n 1.0.2

If I remove the martino:i18n-conf 0.3.1 occurs the error.

**Comment by martinopic** [comment]
I think you are right and I have to use `api.imply` in addition to `api.use` to make I18NConf automatically available on Iron Router i18n loading (which is needed because configuration depends on that). This bus has an easy workaround which is just manually adding the package but it's stilla but, will be fixed in next release.

**Comment by PauloSegundo** [comment]
Sorry, i am using the latest version and still have same problem if I remove martino:i18n-conf
